language: python
sudo: false

install:
  - pip install pytest xmlrunner
  - curl -s https://raw.githubusercontent.com/report-ci/scripts/master/annotate.py > annotate.py
  - set -o pipefail

env:
  - TEST_CMD="pytest pytest_example.py --junit-xml=pytest_example.xml" FRAMEWORK=PyTest SED="'s/^E   //m'"
  - TEST_CMD="python pyunit.py" SCRIPT_OPT="--framework=pyunit" FRAMEWORK=PyUnit SED="''"

script:
  - $TEST_CMD 2>&1 | set $SED | python annotate.py --tool python --tee --name "$FRAMEWORK log"

after_script:
  - curl -s https://raw.githubusercontent.com/report-ci/scripts/master/upload.py | python - $SCRIPT_OPT